language: minimal

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: Build and Push
      script:
        - docker build -t udagram-api-feed ./udagram-api-feed
        - docker tag udagram-api-feed $DOCKER_USERNAME/udagram-api-feed
        - docker push $DOCKER_USERNAME/udagram-api-feed
      if: branch = master

    - stage: Build and Push
      script:
        - docker build -t udagram-api-user ./udagram-api-user
        - docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user
        - docker push $DOCKER_USERNAME/udagram-api-user
      if: branch = master

    - stage: Build and Push
      script:
        - docker build -t udagram-frontend ./udagram-frontend
        - docker tag udagram-frontend $DOCKER_USERNAME/udagram-frontend
        - docker push $DOCKER_USERNAME/udagram-frontend
      if: branch = master

    - stage: Build and Push
      script:
        - docker build -t reverseproxy ./udagram-reverseproxy
        - docker tag reverseproxy $DOCKER_USERNAME/reverseproxy
        - docker push $DOCKER_USERNAME/reverseproxy
      if: branch = master