apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: tungnguyenls/udagram-api-feed:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRESS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRESS_USERNAME
            - name: POSTGRESS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRESS_PASSWORD
            - name: POSTGRESS_DB
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRESS_DB
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_REGION
            - name: AWS_PROFILE
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_PROFILE
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_BUCKET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: JWT_SECRET
          volumeMounts:
            - name: aws-secret
              mountPath: '/root/.aws/'
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret