apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/tungnguyenls/udagram-frontend:latest
          ports:
          - containerPort: 80
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: env-config
      restartPolicy: Always
